from os import PathLike
from os.path import abspath, dirname, join
from shutil import which
from tempfile import NamedTemporaryFile

from padelpy2.utils import popen_timeout


PADEL_PATH = join(
    dirname(abspath(__file__)),
    "PaDEL-Descriptor",
    "PaDEL-Descriptor.jar"
)


def padeldescriptor(
        maxruntime: int = -1,
        waitingjobs: int = -1,
        threads: int = -1,
        d_2d: bool = False,
        d_3d: bool = False,
        config: PathLike = None,
        convert3d: bool = False,
        descriptortypes: PathLike = None,
        detectaromaticity: bool = False,
        mol_dir: PathLike = None,
        d_file: PathLike = None,
        fingerprints: bool = False,
        log: bool = False,
        maxcpdperfile: int = 0,
        removesalt: bool = False,
        retain3d: bool = False,
        retainorder: bool = True,
        standardizenitro: bool = False,
        standardizetautomers: bool = False,
        tautomerlist: PathLike = None,
        usefilenameasmolname: bool = False,
        sp_timeout: int = None,
        headless: bool = True,
        use_tempfile: bool = False
     ) -> PathLike | None:
    """
    Execute PaDEL-Descriptor with specified parameters.

    Parameters
    ----------
    maxruntime : int, optional
        Maximum running time per molecule (in milliseconds). Use -1 for
        unlimited. Default is -1.
    waitingjobs : int, optional
        Maximum number of jobs to store in queue for worker threads to process.
        Use -1 to set it to 50*Max threads. Default is -1.
    threads : int, optional
        Maximum number of threads to use. Use -1 to use as many threads as the
        number of CPU cores. Default is -1.
    d_2d : bool, optional
        Calculate 1D and 2D descriptors. Default is False.
    d_3d : bool, optional
        Calculate 3D descriptors. Default is False.
    config : PathLike, optional
        Configuration file. Default is None.
    convert3d : bool, optional
        Convert molecule to 3D. Default is False.
    descriptortypes : PathLike, optional
        Descriptor types file. Default is None.
    detectaromaticity : bool, optional
        Remove existing aromaticity information and automatically detect
        aromaticity in the molecule before calculation of descriptors. Default
        is False.
    mol_dir : PathLike, optional
        Set directory containing structural files, or a path to a file. Default
        is None.
    d_file : PathLike, optional
        Set file to save calculated descriptors. Default is None.
    fingerprints : bool, optional
        Calculate fingerprints. Default is False.
    log : bool, optional
        Create a log file. Name of log file is the name of the descriptors file
        with a .log extension. Default is False.
    maxcpdperfile : int, optional
        Maximum number of compounds to be stored in each descriptor file. Use 0
        for unlimited. Default is 0.
    removesalt : bool, optional
        Remove salt from molecule. Default is False.
    retain3d : bool, optional
        Retain 3D coordinates when standardizing structure. However, this may
        prevent some structures from being standardized. Default is False.
    retainorder : bool, optional
        Retain order of molecules in structural files for descriptor file. This
        may lead to large memory use if descriptor calculations are stuck at
        one molecule as the others will not be written to file and cleared from
        memory. Default is True.
    standardizenitro : bool, optional
        Standardize nitro groups to N(:O):O. Default is False.
    standardizetautomers : bool, optional
        Standardize tautomers. Default is False.
    tautomerlist : PathLike, optional
        SMIRKS tautomers file. Default is None.
    usefilenameasmolname : bool, optional
        Use filename (minus the extension) as molecule name. Default is False.
    sp_timeout : int, optional
        Timeout for subprocess execution in seconds. Default is None (no
        timeout).
    headless : bool, optional
        Run PaDEL-Descriptor in headless mode. Default is True.
    use_tempfile : bool, optional
        Use a temporary file for output if `d_file` is not specified. Default
        is False.

    Returns
    -------
    PathLike or None
        The path to the descriptors file generated by PaDEL-Descriptor, or None
        if no file is generated.
    """

    if which("java") is None:
        raise ReferenceError("Java JRE 6+ not found.")

    if headless:
        command = f"java -Djava.awt.headless=true -jar {PADEL_PATH}"
    else:
        command = f"java -jar {PADEL_PATH}"

    if d_file is None and use_tempfile:
        with NamedTemporaryFile("w", delete=False, suffix=".csv") as outfile:
            d_file = outfile.name

    command += f" -maxruntime {maxruntime}"
    command += f" -waitingjobs {waitingjobs}"
    command += f" -threads {threads}"
    command += f" -maxcpdperfile {maxcpdperfile}"
    if d_2d:
        command += " -2d"
    if d_3d:
        command += " -3d"
    if config:
        command += f" -config {config}"
    if convert3d:
        command += " -convert3d"
    if descriptortypes:
        command += f" -descriptortypes {descriptortypes}"
    if detectaromaticity:
        command += " -detectaromaticity"
    if mol_dir:
        command += f" -dir {mol_dir}"
    if d_file:
        command += f" -file {d_file}"
    if fingerprints:
        command += " -fingerprints"
    if log:
        command += " -log"
    if removesalt:
        command += " -removesalt"
    if retain3d:
        command += " -retain3d"
    if retainorder:
        command += " -retainorder"
    if standardizenitro:
        command += " -standardizenitro"
    if standardizetautomers:
        command += " -standardizetautomers"
    if tautomerlist:
        command += f" -tautomerlist {tautomerlist}"
    if usefilenameasmolname:
        command += f" -usefilenameasmolname"

    _, err = popen_timeout(command, sp_timeout)
    if err != b"":
        raise RuntimeError(
            f"PaDEL-Descriptor encountered an error: {err.decode('utf-8')}"
        )
    return d_file
